config/routes.rb
Rails.application.routes.draw do

  get 'about', to:'pages#about', as: :about
  get 'contact', to:'pages#contact', as: :contact

  resources :tournaments

        resources :teams




  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord
 belongs_to :tournament
 has_many :users
validates :name, presence: true

end

app/models/tournament.rb
class Tournament < ApplicationRecord

  has_one_attached :photo
  has_many :teams

  validates :name, presence: true
  validates :start_tournament, presence: true
  validates :end_tournament, presence: true
  validates :photo, presence: true
  validates :activity, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  belongs_to :team

  validates :name, presence: true
  validates :avatar, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def show
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    #@team.user = current_user
    #@team = current_user.team.build.(team_params)
    if @team.save
      redirect_to teams_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @team.update(team_params)
    redirect_to teams_path
  end

  def destroy
    @team.destroy
    redirect_to teams_path
  end

  private

  def team_params
    params.require(:team).permit(:name, :tournament_id, :user)
  end

   def set_team
    @team = Team.find(params[:id])
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  def index
    @tournaments = Tournament.all
  end

  def show
  end

  def new
    @tournament = Tournament.new
  end

  def create
    Tournament.create(tournament_params)
    redirect_to tournaments_path
  end

  def edit
  end

  def update
    @tournament.update(tournament_params)
    redirect_to tournaments_path
  end

  def destroy
    @tournament.destroy
    redirect_to tournaments_path
  end

  private

  def tournament_params
    params.require(:tournament).permit(:name, :start_tournament, :end_tournament, :photo, :activity)
  end

   def set_tournament
    @tournament = Tournament.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TOURNAMENT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<ul>
  <li><%= link_to "Tous les tournois", tournaments_path  %></li>
  <li><%= link_to "Toutes les équipes", teams_path  %></li>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://img.icons8.com/doodle/96/000000/first-place-ribbon--v1.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar.key  , height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tournaments/edit.html.erb
<%= simple_form_for @tournament do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file%>
  <%= f.input :start_tournament %>
  <%= f.input :end_tournament %>
  <%= f.input :activity%>
  <%= f.button :submit, "Créer mon tournoi" %>
<% end  %>

app/views/tournaments/index.html.erb
<h1>Les tournois</h1>

<%= link_to "Créer mon tournoi", new_tournament_path %>

<% @tournaments.each do |tournament| %>
  <h2><%= tournament.name %></h2>
  <p><%= cl_image_tag tournament.photo.key , height: 400, width: 400, crop: :fill%></p>
  <p><%= tournament.start_tournament%></p>
  <p><%= tournament.end_tournament%></p>
  <p><%= tournament.activity%></p>
  <p><%= link_to "Aller voir le tournoi", tournament_path(tournament)  %></p>
  <p><%= link_to "Supprimer", tournament_path(tournament), method: :delete, data: { confirm: "Are you sure?" }   %></p>

<% end %>

app/views/tournaments/new.html.erb
<%= simple_form_for @tournament do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file%>
  <%= f.input :start_tournament %>
  <%= f.input :end_tournament %>
  <%= f.input :activity%>
  <%= f.button :submit, "Créer mon tournoi" %>
<% end  %>

app/views/tournaments/show.html.erb
  <h2><%= @tournament.name %></h2>
  <p><%= cl_image_tag @tournament.photo.key , height: 400, width: 400, crop: :fill%></p>
  <p>Début du tournoi : <%=  @tournament.start_tournament%></p>
  <p>Fin du tournoi : <%= @tournament.end_tournament%></p>
  <p>Activité :<%= @tournament.activity%></p>
  <p>Equipes participantes :</p>
  <% @tournament.teams.each do |team|  %>
  <ul>
    <li><%= link_to team.name , team_path(team)%></li>

  </ul>
    <% end %>
<p><%= link_to "Tous les tournois" , tournaments_path  %></p>